### ISSUE TITLE
Imagens quebradas no menu de baixo

### ISSUE THREAD

**Issue by 403thi** [athoskenew/pouorochinho#1]
Ao rodar o código fonte, os ícones do menu de baixo estão quebrados e em branco.

![image](https://github.com/athoskenew/pouorochinho/assets/82724852/28e0d64f-8c8c-46a3-a378-f7a308c3b8ba)

O que acontece é que no arquivo `pourochi.kv` essas imagens estão sendo setadas com a extensão `.jpg`, mas as mesmas estão salvas como `.png` na pasta [source/images](https://github.com/athoskenew/pouorochinho/tree/main/source/images).

**Comment by athoskenew** [comment]
valeu pelo aviso man, antes de subir o código corrigi todas as imagens e essas aí mudaram de extensão, vou aceitar o pr da correção.
